# Site Settigs

title: Bootstrapped Indian Co.
email: io@sabid.in
description: >- # this means to ignore newlines until "baseurl:"
  The honest story of running a bootstrapped startup
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author:
  name: Subin Abid
  email: "io@sabid.in"

# Social
social:
  linkedin_username:  subinabid
  insta_username:  5.hydroxy.tryptamine

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
